name: Signs and Store Assertion Document
description: Run Smoke Tests for the project

inputs:
  assertion-doc:
    description: Assertion Document in JSON format
    required: true

runs:
  using: composite
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

    - name: Generate Checksum
      id: sign
      run: |
        cosign_binary=${COSIGN_BIN:-"cosign"}

        # Get assertion json file basename
        assertiondoc=$(basename "${{ inputs.assertion-doc }}")
        sha256sum "${assertiondoc}" >> "${assertiondoc}_checksum.txt"
        checksum_file="${assertiondoc}_checksum.txt"
        bundle_file="${assertiondoc}.bundle.json"

        # Sign
        ${cosign_binary} sign-blob "${checksum_file}" --bundle="${bundle_file}" --output-signature="${checksum_file}.sig" --output-certificate="${checksum_file}.pem" -y

        # Create tarball
        tarball_name="${assertiondoc}.tar.gz"
        tar -czf "${tarball_name}" "${assertiondoc}" "${checksum_file}" "${bundle_file}"

        # Create output var
        echo "assertiontar=${tarball_name}" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
      shell: bash

    - name: Store assertion document
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ steps.sign.outputs.assertiontar }}
        path: ${{ steps.sign.outputs.assertiontar }}
        retention-days: 7
