name: Signs and Store Assertion Document
description: Run Smoke Tests for the project

inputs:
  assertion-doc:
    description: Assertion Document in JSON format
    required: true

runs:
  using: composite
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2

    - name: Generate Checksum
      id: sign
      run: |
        cosign_binary=${COSIGN_BIN:-"cosign"}
        assertiondoc=$(basename "${{ inputs.assertion-doc }}")
        sha256sum "${assertiondoc}" >> "${assertiondoc}_checksum.txt"
        checksum_file="${assertiondoc}_checksum.txt"
        ${cosign_binary} sign-blob "${checksum_file}" --output-signature="${checksum_file}.sig" --output-certificate="${checksum_file}.pem" -y
        tarball_name="${assertiondoc}.tar.gz"
        tar -czf "${tarball_name}" "${assertiondoc}" "${checksum_file}" "${checksum_file}.sig" "${checksum_file}.pem"

        #sha256sum ${{ inputs.assertion-doc }} >> "${{ inputs.assertion-doc }}_checksum.txt"
        #checksum_file="${{ inputs.assertion-doc }}_checksum.txt"
        #${cosign_binary} sign-blob "${checksum_file}" --output-signature="${checksum_file}.sig" --output-certificate="${checksum_file}.pem" -y
        #tar -cvf assertion.tar assertion*
        #tarball_name=$(basename "${{ inputs.assertion-doc }}")
        #tar -cvf ${{ inputs.assertion-doc }}.tar ${{ inputs.assertion-doc }}_*
        #echo "assertiontar=$(find -type f -name "assertion.tar" | head -n 1)" >> $GITHUB_OUTPUT
        #echo "assertiontar=${{ inputs.assertion-doc }}.tar" >> $GITHUB_OUTPUT
        echo "assertiontar=${tarball_name}" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
      shell: bash

    - name: Store assertion document
      uses: actions/upload-artifact@v4
      with:
        name: assertion
        path: ${{ steps.sign.outputs.assertiontar }}
        retention-days: 7
