name: 'SBOM Document'
description: 'Generates, signs and stores SBOM document'

inputs:
  binary-name:
    description: A binary to generate SBOM
    required: true

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0
      with:
        name: ${{ inputs.binary-name }}

    - name: Download Syft
      id: syft
      uses: anchore/sbom-action/download-syft@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10

    - name: Generate SBOM file
      id: sbom
      run: |
        syft scan file:"${{ inputs.binary-name }}" -o spdx-json > "${{ inputs.binary-name }}.spdx.json"
        cat "${{ inputs.binary-name }}.spdx.json" | jq .
        echo "sbom-doc=${{ inputs.binary-name }}.spdx.json" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      shell: bash

    - name: Install Cosign
      uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2

    - name: Generate checksum and sign SBOM file
      id: sign
      run: |
        cosign_binary=${COSIGN_BIN:-"cosign"}

        sha256sum "${{ steps.sbom.outputs.sbom-doc }}" >> "${{ steps.sbom.outputs.sbom-doc }}_checksum.txt"
        checksum_file="${{ steps.sbom.outputs.sbom-doc }}_checksum.txt"

        # Sign
        ${cosign_binary} sign-blob "${checksum_file}" --output-signature="${checksum_file}.sig" --output-certificate="${checksum_file}.pem" -y

        # Create tarball
        tarball_name="${{ inputs.binary-name }}.tar.gz"
        tar -czf "${tarball_name}" "${{ steps.sbom.outputs.sbom-doc }}" "${checksum_file}" "${checksum_file}.sig" "${checksum_file}.pem"

        # Create output var
        echo "sbomtar=${tarball_name}" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
      shell: bash


    - name: Store SBOM document
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ steps.sign.outputs.sbomtar }}
        path: ${{ steps.sign.outputs.sbomtar }}
        retention-days: 1
