name: 'SBOM from binary'
description: 'Generates, signs and stores SBOM document'

inputs:
  binary-name:
    description: A binary to generate SBOM
    required: true
  product-name:
    description: Name of the product, for example 'agent', 'nic'
    required: true
  ref:
    description: The branch, tag or SHA to checkout
    required: true
  release-version:
    description: Product release version (semver), for example v0.1.1
    required: true
  language:
    description: Programming language, for example golang, java, rust
    required: false
    default: golang
  az-client-id:
    description: Azure client id
    required: true
  az-tenant-id:
    description: Azure tenant id
    required: true
  az-subscription-id:
    description: Azure subscription id
    required: true
  az-storage-account:
    description: Azure storage account for SBOM documents
    required: true
  artifactory-user:
    description: Artifactory user
    required: true
  artifactory-token:
    description: Artifactory token
    required: true
  save_in_github:
    description: Stores SBOM document as GitHub artifact
    required: false
    default: "false"
  retention_days:
    description: How long (days) artifacts are stored in GitHub
    required: true
    default: "1"
  save_in_az:
    description: Stores SBOM docs in Azure
    required: true
    default: "true"
  debug:
    description: Show generated SBOM in GitHub workflow log
    required: true
    default: "false"


runs:
  using: composite
  steps:
    - name: Download Syft
      id: syft
      uses: anchore/sbom-action/download-syft@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10

    - name: Generate SBOM from Go binary
      id: sbom
      run: |
        binaryname=$(basename "${{ inputs.binary-name }}")

        # Scan binary and generate SBOM doc
        syft scan file:"${binaryname}" -o spdx-json > "${binaryname}.bin.spdx.json"

        echo "binary=${binaryname}" >> $GITHUB_OUTPUT
        echo "sbom-doc-bin=${binaryname}.bin.spdx.json" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      shell: bash
      env:
        SYFT_OUTPUT: "spdx-json"
        SYFT_ENRICH: "golang"
        SYFT_SOURCE_SUPPLIER: "F5 Networks"
        SYFT_GOLANG_MAIN_MODULE_VERSION_FROM_LD_FLAGS: "true"
        SYFT_GOLANG_PROXY: "https://${{ inputs.artifactory-user }}:${{ inputs.artifactory-token }}@azr.artifactory.f5net.com/artifactory/api/go/f5-nginx-go-local-approved-dependency"
        SYFT_SOURCE_NAME: ${{ inputs.product-name }}
        SYFT_SOURCE_VERSION: ${{ inputs.release-version }}
        SYFT_SOURCE_FILE_DIGESTS: "SHA-256,SHA-512"

    - name: Show SBOM doc in workflow log
      if: inputs.debug == 'true'
      run: |
        cat "${{ steps.sbom.outputs.sbom-doc-bin }}" | jq .
      shell: bash

    - name: Install Cosign
      uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

    - name: Generate checksum and sign SBOM for binary
      id: sign
      run: |
        cosign_binary=${COSIGN_BIN:-"cosign"}

        sbomdoc=$(basename "${{ steps.sbom.outputs.sbom-doc-bin }}")
        sha256sum "${sbomdoc}" >> "${sbomdoc}_checksum.txt"
        checksum_file=${sbomdoc}_checksum.txt
        bundle_file="${{ steps.sbom.outputs.sbom-doc-bin }}.bundle.json"

        # Sign
        ${cosign_binary} sign-blob "${sbomdoc}" --bundle="${bundle_file}" --output-signature="${checksum_file}.sig" --output-certificate="${checksum_file}.pem" -y

        # Create tarball
        tarball_name="${{ inputs.product-name }}_${{ inputs.release-version }}_sbom_bin.tar.gz"
        tar -czf "${tarball_name}" "${sbomdoc}" "${checksum_file}" "${bundle_file}"

        # Create output var
        echo "sbomtar=${tarball_name}" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
      shell: bash

    - name: Store SBOM document in GitHub
      if: inputs.save_in_github == 'true'
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ steps.sign.outputs.sbomtar }}
        path: ${{ steps.sign.outputs.sbomtar }}
        retention-days: 1

    - name: Azure login
      if: inputs.save_in_az == 'true'
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.az-client-id }}
        tenant-id: ${{ inputs.az-tenant-id }}
        subscription-id: ${{ inputs.az-subscription-id }}

    - name: Setup Azure variables
      if: inputs.save_in_az == 'true'
      id: azvars
      run: |
        echo "Setting variables for AZ upload"
        echo "az-container-name=cylon-indigo-generic-release-sbom" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      shell: bash

    - name: Upload SBOM document to Azure
      if: inputs.save_in_az == 'true'
      uses: azure/CLI@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956 # v2.2.0
      with:
        inlineScript: |
          echo -n "Uploading SBOM file ${{ steps.sbom.outputs.sbomtar }} to Azure storage"
          az storage blob upload --auth-mode=login \
            --account-name ${{ inputs.az-storage-account }} \
            --container-name ${{ steps.azvars.outputs.az-container-name }} \
            -f ./${{ steps.sign.outputs.sbomtar }} \
            --overwrite -n poc/nginx-security-test/${{ inputs.product-name }}/${{ inputs.release-version }}/${{ steps.sign.outputs.sbomtar }}
