name: 'CycloneDX SBOM Document'
description: 'Generates, signs and stores CycloneDX SBOM document'

inputs:
  binary-name:
    description: A binary to introspect and generate SBOM
    required: true
  # az-vault-client-id:
  #   description: Azure client ID
  #   required: true
  # az-vault-tenant-id:
  #   description: Azure tenant ID
  #   required: true
  # az-vault-subscription-id:
  #   description: Azure subscription ID
  #   required: true
  # az-client-id:
  #   description: Azure Client ID
  #   required: true
  # az-tenant-id:
  #   description: Azure Tenant ID
  #   required: true
  # az-subscription-id:
  #   description: Azure Subscription ID
  #   required: true
  product-name:
    description: Name of the product, for example agent
    required: true
  main-path:
    description: Path to the Go main module in the repo, for example cmd/ptdcli
    required: true
  release-version:
    description: Product release version (semver), for example v0.1.1
    required: true


runs:
  using: composite
  steps:
    - name: Checkout Go repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: 'stable'
        cache: false

    - name: Download cyclonedx-gomod
      uses: CycloneDX/gh-gomod-generate-sbom@efc74245d6802c8cefd925620515442756c70d8f # v2.0.0
      with:
        version: v1.9.0

    - name: Generate SBOM for app
      id: sbom-app
      run: |
        cyclonedx-gomod app -json -output "${{ inputs.product-name }}-app.bom.json" -packages -files -licenses -main ${{ inputs.main-path }}
        echo "sbom-app=${{ inputs.product-name }}-app.bom.json" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      shell: bash

    # - name: Generate SBOM file
    #   id: sbom
    #   run: |
    #     binaryname=$(basename "${{ inputs.binary-name }}")

    #     # Scan binary and generate SBOM doc
    #     syft scan file:"${binaryname}" -o spdx-json > "${binaryname}.spdx.json"

    #     # Temporary list the doc for testing purpose
    #     cat "${binaryname}.spdx.json" | jq .

    #     echo "binary=${binaryname}" >> $GITHUB_OUTPUT
    #     echo "sbom-doc=${binaryname}.spdx.json" >> $GITHUB_OUTPUT
    #     cat $GITHUB_OUTPUT
    #   shell: bash
      
    # - name: Install Cosign
    #   uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

    # - name: Generate checksum and sign SBOM file
    #   id: sign
    #   run: |
    #     cosign_binary=${COSIGN_BIN:-"cosign"}

    #     sbomdoc=$(basename "${{ steps.sbom.outputs.sbom-doc }}")
    #     sha256sum "${sbomdoc}" >> "${sbomdoc}_checksum.txt"
    #     checksum_file=${sbomdoc}_checksum.txt
    #     bundle_file="${{ steps.sbom.outputs.binary }}.bundle.json"

    #     # Sign
    #     ${cosign_binary} sign-blob "${sbomdoc}" --bundle="${bundle_file}" --output-signature="${checksum_file}.sig" --output-certificate="${checksum_file}.pem" -y

    #     # Create tarball
    #     tarball_name="${{ steps.sbom.outputs.binary }}_sbom.tar.gz"
    #     tar -czf "${tarball_name}" "${sbomdoc}" "${checksum_file}" "${bundle_file}"

    #     # Create output var
    #     echo "sbomtar=${tarball_name}" >> $GITHUB_OUTPUT
    #     echo $GITHUB_OUTPUT
    #   shell: bash

    # - name: Store SBOM document
    #   uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
    #   with:
    #     name: ${{ steps.sign.outputs.sbomtar }}
    #     path: ${{ steps.sign.outputs.sbomtar }}
    #     retention-days: 1

    # - name: Azure login
    #   uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
    #   with:
    #     client-id: ${{ inputs.az-client-id }}
    #     tenant-id: ${{ inputs.az-tenant-id }}
    #     subscription-id: ${{ inputs.az-subscription-id }}

    # - name: Setup AZ vars
    #   id: secrets
    #   run: |
    #     echo "Setting secrets for job"
    #     echo "AZ_BUCKET_NAME=${}" >> $GITHUB_OUTPUT
    #     echo "AZ_STORAGE_ACCOUNT=${}" >> $GITHUB_OUTPUT

    #   shell: bash

    # - name: Azure login for upload
    #   uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
    #   with:
    #     client-id: ${{ inputs.az-client-it }}
    #     tenant-id: ${{ inputs.az-tenant-id }}
    #     subscription-id: ${{ inputs.az-subscription-id }}

    # - name: Upload SBOM document to AZ
    #   uses: azure/CLI@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956 # v2.2.0
    #   with:
    #     inlineScript: |
    #       echo -n "Uploading SBOM file ${{ steps.sign.outputs.sbomtar }} to AZ storage"

    #       #
    #       # az storage blob upload --auth-mode=login -f ${{ steps.sign.outputs.sbomtar }} -c ${{ steps.secrets.outputs.AZURE_BUCKET_NAME }} \
    #       #         --account-name ${{ steps.secrets.outputs.AZURE_STORAGE_ACCOUNT }} --overwrite -n nginx-security-test/${{ steps.sign.outputs.sbomtar }}