name: Mend

on:
  push:
    branches:
      - main
    paths-ignore:
     - site/**
     - examples/**
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false
        default: main
  workflow_call:
    # inputs:
    #  branch:
    #    type: string
    #    required: true

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Mend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch && inputs.branch || github.ref }}

      - name: Download agent
        run: curl -fsSLJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar

      - name: Verify JAR
        run: jarsigner -verify wss-unified-agent.jar

      - name: Scan and upload
        env:
          WS_WSS_URL: "https://f5.whitesourcesoftware.com/agent"
          WS_APIKEY: "${{ secrets.WS_APIKEY_NGINX }}"
          PRODUCT_NAME: nginx-tiger-demo1_${{ inputs.branch && inputs.branch || github.ref_name }}
          PROJECT_NAME: tiger-demo1
        #run: java -jar wss-unified-agent.jar -noConfig true -wss.url $WS_WSS_URL -apiKey $WS_APIKEY -product $PRODUCT_NAME -project $PROJECT_NAME -d .
        run: |
          java -jar wss-unified-agent.jar \
          -noConfig true \
          -wss.url https://api.whitesourcesoftware.com/agent \
          -apiKey ${{ secrets.WSS_API_KEY }} \
          -product "${{ env.PRODUCT_NAME }}" \
          -project "${{ env.PROJECT_NAME }}" \
          -d .
        